## Import Polars

In [2]:
# pip install polars
# poetry add polars
# uv add polars

In [3]:
import polars as pl

## Read Data into DataFrame

In [4]:
COLUMN_NAMES = [
        "id", "price", "date", "postcode", "property_type",
        "old_new", "duration", "paon", "saon", "street",
        "locality", "town_city", "district", "county",
        "ppd_category", "record_type",
    ]

In [5]:
land_registry_data = pl.read_csv(
    source="../../data/land_registry_data/pp-*.csv",
    has_header=False,
    new_columns=COLUMN_NAMES,
    infer_schema=True,
    null_values=[""],
)

In [6]:
land_registry_data

shape: (10_002_480, 16)
┌────────────┬─────────┬────────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ price   ┆ date       ┆ postcode ┆ … ┆ district  ┆ county    ┆ ppd_categ ┆ record_ty │
│ ---        ┆ ---     ┆ ---        ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ory       ┆ pe        │
│ str        ┆ i64     ┆ str        ┆ str      ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│            ┆         ┆            ┆          ┆   ┆           ┆           ┆ str       ┆ str       │
╞════════════╪═════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ {3E0330F0- ┆ 103750  ┆ 2016-09-21 ┆ CF62 6NT ┆ … ┆ THE VALE  ┆ THE VALE  ┆ A         ┆ A         │
│ 76C8-8D89- ┆         ┆ 00:00      ┆          ┆   ┆ OF        ┆ OF        ┆           ┆           │
│ E050-A8C06 ┆         ┆            ┆          ┆   ┆ GLAMORGAN ┆ GLAMORGAN ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ {3E0330F0- ┆ 165000  ┆ 2016-09-16 ┆ NP10 9DN ┆ … ┆ NEWPORT   ┆ NEWPORT   ┆ A         ┆ A         │
│ 76C9-8D89- ┆         ┆ 00:00      ┆          ┆   ┆           ┆           ┆           ┆           │
│ E050-A8C06 ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ {3E0330F0- ┆ 90000   ┆ 2016-09-02 ┆ SA11 3SD ┆ … ┆ NEATH     ┆ NEATH     ┆ A         ┆ A         │
│ 76CA-8D89- ┆         ┆ 00:00      ┆          ┆   ┆ PORT      ┆ PORT      ┆           ┆           │
│ E050-A8C06 ┆         ┆            ┆          ┆   ┆ TALBOT    ┆ TALBOT    ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ {3E0330F0- ┆ 105000  ┆ 2016-08-22 ┆ CF63 2QN ┆ … ┆ THE VALE  ┆ THE VALE  ┆ A         ┆ A         │
│ 76CB-8D89- ┆         ┆ 00:00      ┆          ┆   ┆ OF        ┆ OF        ┆           ┆           │
│ E050-A8C06 ┆         ┆            ┆          ┆   ┆ GLAMORGAN ┆ GLAMORGAN ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ {3E0330F0- ┆ 67500   ┆ 2016-08-30 ┆ NP18 1HA ┆ … ┆ TORFAEN   ┆ TORFAEN   ┆ A         ┆ A         │
│ 76CC-8D89- ┆         ┆ 00:00      ┆          ┆   ┆           ┆           ┆           ┆           │
│ E050-A8C06 ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …          ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ {36A61A95- ┆ 177500  ┆ 2025-04-30 ┆ NR1 3SB  ┆ … ┆ NORWICH   ┆ NORFOLK   ┆ B         ┆ A         │
│ 56B0-DEF2- ┆         ┆ 00:00      ┆          ┆   ┆           ┆           ┆           ┆           │
│ E063-4704A ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ {36A61A95- ┆ 113501  ┆ 2025-05-02 ┆ PE30 5HJ ┆ … ┆ KING'S    ┆ NORFOLK   ┆ B         ┆ A         │
│ 56B2-DEF2- ┆         ┆ 00:00      ┆          ┆   ┆ LYNN AND  ┆           ┆           ┆           │
│ E063-4704A ┆         ┆            ┆          ┆   ┆ WEST      ┆           ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆ NORFOLK   ┆           ┆           ┆           │
│ {36A61A95- ┆ 1100000 ┆ 2025-04-24 ┆ NR16 1QH ┆ … ┆ SOUTH     ┆ NORFOLK   ┆ B         ┆ A         │
│ 56B5-DEF2- ┆         ┆ 00:00      ┆          ┆   ┆ NORFOLK   ┆           ┆           ┆           │
│ E063-4704A ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ {36A61A95- ┆ 250000  ┆ 2025-03-31 ┆ NR7 8ES  ┆ … ┆ BROADLAND ┆ NORFOLK   ┆ B         ┆ A         │
│ 56B7-DEF2- ┆         ┆ 00:00      ┆          ┆   ┆           ┆           ┆           ┆           │
│ E063-4704A ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│ {36A61A95- ┆ 175000  ┆ 2025-04-17 ┆ PE14 9EA ┆ … ┆ KING'S    ┆ NORFOLK   ┆ B         ┆ A         │
│ 56B9-DEF2- ┆         ┆ 00:00      ┆          ┆   ┆ LYNN AND  ┆           ┆           ┆           │
│ E063-4704A ┆         ┆            ┆          ┆   ┆ WEST      ┆           ┆           ┆           │
│ …          ┆         ┆            ┆          ┆   ┆ NORFOLK   ┆           ┆           ┆           │
└────────────┴─────────┴────────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
land_registry_data.describe()

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ statistic ┆ id        ┆ price     ┆ date      ┆ … ┆ district ┆ county    ┆ ppd_categ ┆ record_ty │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---       ┆ ory       ┆ pe        │
│ str       ┆ str       ┆ f64       ┆ str       ┆   ┆ str      ┆ str       ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 10002480  ┆ 1.000248e ┆ 10002480  ┆ … ┆ 10002480 ┆ 10002480  ┆ 10002480  ┆ 10002480  │
│           ┆           ┆ 7         ┆           ┆   ┆          ┆           ┆           ┆           │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0         ┆ … ┆ 0        ┆ 0         ┆ 0         ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ mean      ┆ null      ┆ 372035.51 ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│           ┆           ┆ 4483      ┆           ┆   ┆          ┆           ┆           ┆           │
│ std       ┆ null      ┆ 1.6258e6  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ min       ┆ {01EB45EF ┆ 1.0       ┆ 2016-01-0 ┆ … ┆ ADUR     ┆ BATH AND  ┆ A         ┆ A         │
│           ┆ -612C-40F ┆           ┆ 1 00:00   ┆   ┆          ┆ NORTH     ┆           ┆           │
│           ┆ 3-E063-47 ┆           ┆           ┆   ┆          ┆ EAST      ┆           ┆           │
│           ┆ 04A…      ┆           ┆           ┆   ┆          ┆ SOMERSET  ┆           ┆           │
│ 25%       ┆ null      ┆ 160000.0  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ 250000.0  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ 390000.0  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ max       ┆ {FFA361DB ┆ 9e8       ┆ 2025-12-3 ┆ … ┆ YORK     ┆ YORK      ┆ B         ┆ A         │
│           ┆ -9CCE-8A0 ┆           ┆ 1 00:00   ┆   ┆          ┆           ┆           ┆           │
│           ┆ 3-E053-48 ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ 04A…      ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [8]:
land_registry_data = (
    land_registry_data
    .with_columns(
        pl.col("date").str.to_date(format="%Y-%m-%d %H:%M"),
    )
)

In [9]:
land_registry_data = land_registry_data.with_columns(
    pl.col("property_type").replace({
        "D": "Detached",
        "S": "Semi-Detached",
        "T": "Terraced",
        "F": "Flat",
        "O": "Other",
    }).alias("property_type")
)

In [10]:
land_registry_data["property_type"].value_counts()

shape: (5, 2)
┌───────────────┬─────────┐
│ property_type ┆ count   │
│ ---           ┆ ---     │
│ str           ┆ u32     │
╞═══════════════╪═════════╡
│ Terraced      ┆ 2696606 │
│ Semi-Detached ┆ 2625078 │
│ Flat          ┆ 1794725 │
│ Other         ┆ 582196  │
│ Detached      ┆ 2303875 │
└───────────────┴─────────┘

In [11]:
land_registry_data = land_registry_data.filter(pl.col("property_type") != "Other")

In [12]:
land_registry_data = (
    land_registry_data
    .with_columns(
        pl.col("date").dt.year().alias("year"),
    )
)

In [13]:
annual_median_price_by_property_type = (
    land_registry_data
    .group_by(["year", "property_type"])
    .agg(
        pl.col("price").median().alias("median_price")
    )
    .sort(["year", "property_type"])
)

In [14]:
annual_median_price_by_property_type

shape: (40, 3)
┌──────┬───────────────┬──────────────┐
│ year ┆ property_type ┆ median_price │
│ ---  ┆ ---           ┆ ---          │
│ i32  ┆ str           ┆ f64          │
╞══════╪═══════════════╪══════════════╡
│ 2016 ┆ Detached      ┆ 306000.0     │
│ 2016 ┆ Flat          ┆ 200000.0     │
│ 2016 ┆ Semi-Detached ┆ 187500.0     │
│ 2016 ┆ Terraced      ┆ 169000.0     │
│ 2017 ┆ Detached      ┆ 322500.0     │
│ …    ┆ …             ┆ …            │
│ 2024 ┆ Terraced      ┆ 220000.0     │
│ 2025 ┆ Detached      ┆ 416100.5     │
│ 2025 ┆ Flat          ┆ 230000.0     │
│ 2025 ┆ Semi-Detached ┆ 270000.0     │
│ 2025 ┆ Terraced      ┆ 225000.0     │
└──────┴───────────────┴──────────────┘

## Visualise the results

In [15]:
import plotly.express as px

In [17]:
px.line(
    annual_median_price_by_property_type,
    x="year",
    y="median_price",
    color="property_type",
    markers=True,
    title="Median Price by Year and Property Type",
    width=800,
    height=600,
)

In [18]:
annual_median_price_by_property_type.write_delta("../../data/price_paid_insights/annual_price_by_property_type", mode="overwrite")

In [21]:
lazy_frame = (
    pl.scan_csv(
    source="../../data/land_registry_data/pp-*.csv",
    has_header=False,
    new_columns=COLUMN_NAMES,
    infer_schema=False,
    null_values=[""])
    .with_columns(
        pl.col("date").str.to_date(format="%Y-%m-%d %H:%M"),
    )
    .with_columns(
        pl.col("property_type").replace({
            "D": "Detached",
            "S": "Semi-Detached",
            "T": "Terraced",
            "F": "Flat",
            "O": "Other",
        }).alias("property_type")
    )
    .filter(pl.col("property_type") != "Other")
    .with_columns(
        pl.col("date").dt.year().alias("year")
    )
    .group_by(["year", "property_type"])
    .agg(
        pl.col("price").median().alias("median_price")
    )
    .sort(["year", "property_type"])
)

In [22]:
lazy_frame

In [23]:
print(lazy_frame.explain())

SORT BY [col("year"), col("property_type")]
  AGGREGATE[maintain_order: false]
    [col("price").median().alias("median_price")] BY [col("year"), col("property_type")]
    FROM
     WITH_COLUMNS:
     [col("date").dt.year().alias("year")]
      FILTER [(col("property_type")) != ("Other")]
      FROM
         WITH_COLUMNS:
         [col("date").str.strptime(["raise"]), col("property_type").replace([["D", "S", … "O"], ["Detached", "Semi-Detached", … "Other"]])]
          Csv SCAN [../../data/land_registry_data/pp-2016.csv, ... 9 other sources]
          PROJECT 3/16 COLUMNS
          ESTIMATED ROWS: 0

In [24]:
lazy_frame.collect()

shape: (40, 3)
┌──────┬───────────────┬──────────────┐
│ year ┆ property_type ┆ median_price │
│ ---  ┆ ---           ┆ ---          │
│ i32  ┆ str           ┆ str          │
╞══════╪═══════════════╪══════════════╡
│ 2016 ┆ Detached      ┆ null         │
│ 2016 ┆ Flat          ┆ null         │
│ 2016 ┆ Semi-Detached ┆ null         │
│ 2016 ┆ Terraced      ┆ null         │
│ 2017 ┆ Detached      ┆ null         │
│ …    ┆ …             ┆ …            │
│ 2024 ┆ Terraced      ┆ null         │
│ 2025 ┆ Detached      ┆ null         │
│ 2025 ┆ Flat          ┆ null         │
│ 2025 ┆ Semi-Detached ┆ null         │
│ 2025 ┆ Terraced      ┆ null         │
└──────┴───────────────┴──────────────┘

In [25]:
# Stream data to parquet
lazy_frame.sink_parquet("../../data/price_paid_insights/land_registry_data.parquet")