# Prepare Demo 

Notebook to run to prepare data ready for demo.

In [16]:
import polars as pl
from pathlib import Path
import xlsxwriter
import duckdb
import json
import uuid

from data_importers import WorldBankDataImporter
importer = WorldBankDataImporter()

In [17]:
DATA_EXPORT_PATH = Path("../data/world_bank")
START_YEAR = 1970
END_YEAR = 2024

SELECTED_COUNTRIES = [
    'GBR', 'FRA', 'DEU', 'ALB', 'NOR', 'GRC',   #Europe & Central Asia
    'JPN', 'CHN',                               #East Asia & Pacific
    'IND', 'PAK', 'BGD',                        #South Asia
    'SAU', 'EGY', 'ISR',                        #Middle East & North Africa
    'NGA', 'ZAF', 'TZA',                        #Sub-Saharan Africa
    'USA', 'CAN', 'MEX',                        #North America
    'CUB', 'DOM', 'CRI', 'BRA', 'ARG', 'CHL',   #Latin America & Caribbean
    'AUS', 'NZL', 'PHL', 'IDN', 'VNM', 'THA'    #East Asia & Pacific
]

SELECTED_INDICATORS = [
    'SP.POP.TOTL',          # Population, total
    'NY.GDP.MKTP.CD',       # GDP (current US$)
    'SE.ADT.LITR.ZS',       # Literacy rate, adult total
    'SL.UEM.TOTL.ZS',       # Unemployment, total (% of  total labor force)
    'SP.DYN.LE00.IN',       # Life expectancy at birth, total (years)
    'EG.USE.PCAP.KG.OE',    # Energy use per capita (kg of oil equivalent)
    'GC.DOD.TOTL.GD.ZS',    # Central government debt, total (% of GDP)
    'NY.GDP.PCAP.CD',       # GDP (US$, per capita)
]

## Get List of Countries

In [18]:
countries = importer.get_countries()

INFO:root:Fetching countries page 1...

In [19]:
countries.columns

['country_code',
 'iso2_code',
 'country_name',
 'region',
 'region_id',
 'income_level',
 'capital_city',
 'longitude',
 'latitude']

In [20]:
countries.filter(pl.col("country_code").is_in(SELECTED_COUNTRIES))

shape: (32, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ country_c ┆ iso2_code ┆ country_n ┆ region    ┆ … ┆ income_le ┆ capital_c ┆ longitude ┆ latitude │
│ ode       ┆ ---       ┆ ame       ┆ ---       ┆   ┆ vel       ┆ ity       ┆ ---       ┆ ---      │
│ ---       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│ str       ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ALB       ┆ AL        ┆ Albania   ┆ Europe &  ┆ … ┆ Upper     ┆ Tirane    ┆ 19.8172   ┆ 41.3317  │
│           ┆           ┆           ┆ Central   ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆ Asia      ┆   ┆ income    ┆           ┆           ┆          │
│ ARG       ┆ AR        ┆ Argentina ┆ Latin     ┆ … ┆ Upper     ┆ Buenos    ┆ -58.4173  ┆ -34.6118 │
│           ┆           ┆           ┆ America & ┆   ┆ middle    ┆ Aires     ┆           ┆          │
│           ┆           ┆           ┆ Caribbean ┆   ┆ income    ┆           ┆           ┆          │
│ AUS       ┆ AU        ┆ Australia ┆ East Asia ┆ … ┆ High      ┆ Canberra  ┆ 149.129   ┆ -35.282  │
│           ┆           ┆           ┆ & Pacific ┆   ┆ income    ┆           ┆           ┆          │
│ BGD       ┆ BD        ┆ Banglades ┆ South     ┆ … ┆ Lower     ┆ Dhaka     ┆ 90.4113   ┆ 23.7055  │
│           ┆           ┆ h         ┆ Asia      ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
│ BRA       ┆ BR        ┆ Brazil    ┆ Latin     ┆ … ┆ Upper     ┆ Brasilia  ┆ -47.9292  ┆ -15.7801 │
│           ┆           ┆           ┆ America & ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆ Caribbean ┆   ┆ income    ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ THA       ┆ TH        ┆ Thailand  ┆ East Asia ┆ … ┆ Upper     ┆ Bangkok   ┆ 100.521   ┆ 13.7308  │
│           ┆           ┆           ┆ & Pacific ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
│ TZA       ┆ TZ        ┆ Tanzania  ┆ Sub-Sahar ┆ … ┆ Lower     ┆ Dodoma    ┆ 35.7382   ┆ -6.17486 │
│           ┆           ┆           ┆ an Africa ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
│ USA       ┆ US        ┆ United    ┆ North     ┆ … ┆ High      ┆ Washingto ┆ -77.032   ┆ 38.8895  │
│           ┆           ┆ States    ┆ America   ┆   ┆ income    ┆ n D.C.    ┆           ┆          │
│ VNM       ┆ VN        ┆ Viet Nam  ┆ East Asia ┆ … ┆ Lower     ┆ Hanoi     ┆ 105.825   ┆ 21.0069  │
│           ┆           ┆           ┆ & Pacific ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
│ ZAF       ┆ ZA        ┆ South     ┆ Sub-Sahar ┆ … ┆ Upper     ┆ Pretoria  ┆ 28.1871   ┆ -25.746  │
│           ┆           ┆ Africa    ┆ an Africa ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Download indicator data

For each country, for each indicator between the years chosen.

In [21]:
data = importer.get_data(
    indicators=SELECTED_INDICATORS,
    countries=SELECTED_COUNTRIES,
    start_year=START_YEAR,
    end_year=END_YEAR
)

INFO:root:Fetching data with skip=0...
INFO:root:Fetching data with skip=1000...
INFO:root:Fetching data with skip=2000...
INFO:root:Fetching data with skip=3000...
INFO:root:Fetching data with skip=4000...
INFO:root:Fetching data with skip=5000...
INFO:root:Fetching data with skip=6000...
INFO:root:Fetching data with skip=7000...
INFO:root:Fetching data with skip=8000...
INFO:root:Fetching data with skip=9000...

In [22]:
data

shape: (9_715, 4)
┌──────────────┬──────┬──────────────────────────┬──────────────┐
│ country_code ┆ year ┆ indicator_code           ┆ value        │
│ ---          ┆ ---  ┆ ---                      ┆ ---          │
│ str          ┆ i64  ┆ str                      ┆ f64          │
╞══════════════╪══════╪══════════════════════════╪══════════════╡
│ VNM          ┆ 2011 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 663.57444    │
│ VNM          ┆ 2018 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 885.646842   │
│ GBR          ┆ 2016 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 2696.97999   │
│ CAN          ┆ 2010 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 7660.754521  │
│ CHL          ┆ 2010 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 1795.68173   │
│ …            ┆ …    ┆ …                        ┆ …            │
│ BGD          ┆ 1970 ┆ WB_WDI_SP_POP_TOTL       ┆ 6.9058894e7  │
│ BRA          ┆ 1970 ┆ WB_WDI_SP_POP_TOTL       ┆ 9.5375651e7  │
│ CAN          ┆ 1970 ┆ WB_WDI_SP_POP_TOTL       ┆ 2.1324e7     │
│ ALB          ┆ 1973 ┆ WB_WDI_SP_POP_TOTL       ┆ 2.296752e6   │
│ VNM          ┆ 2024 ┆ WB_WDI_SP_POP_TOTL       ┆ 1.00987686e8 │
└──────────────┴──────┴──────────────────────────┴──────────────┘

## Capture indicator metadata

In [23]:
indicators = importer.get_indicator_metadata(indicators=SELECTED_INDICATORS)
indicators

INFO:root:Fetching metadata for 8 indicators...

shape: (8, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ indicator_ ┆ indicator_ ┆ aggregatio ┆ definitio ┆ statistic ┆ methodolo ┆ limitatio ┆ relevance │
│ code       ┆ name       ┆ n_method   ┆ n_long    ┆ al_concep ┆ gy        ┆ n         ┆ ---       │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ t         ┆ ---       ┆ ---       ┆ str       │
│ str        ┆ str        ┆ str        ┆ str       ┆ ---       ┆ str       ┆ str       ┆           │
│            ┆            ┆            ┆           ┆ str       ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WB_WDI_GC_ ┆ Central    ┆ Weighted   ┆ Debt is   ┆ Governmen ┆ Governmen ┆ For most  ┆ This      │
│ DOD_TOTL_G ┆ government ┆ average    ┆ the       ┆ t         ┆ t Finance ┆ countries ┆ indicator │
│ D_ZS       ┆ debt,      ┆            ┆ entire    ┆ Financial ┆ statistic ┆ central   ┆ is        │
│            ┆ total…     ┆            ┆ stock of  ┆ Statistic ┆ s …       ┆ gov…      ┆ related   │
│            ┆            ┆            ┆ di…       ┆ …         ┆           ┆           ┆ to G…     │
│ WB_WDI_NY_ ┆ GDP per    ┆ Weighted   ┆ Gross     ┆ The conce ┆ National  ┆ null      ┆ This      │
│ GDP_PCAP_C ┆ capita     ┆ average    ┆ domestic  ┆ ptual     ┆ accounts  ┆           ┆ indicator │
│ D          ┆ (current   ┆            ┆ product   ┆ elements  ┆ are       ┆           ┆ is        │
│            ┆ US$)       ┆            ┆ is the …  ┆ of the…   ┆ compiled… ┆           ┆ related   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ to t…     │
│ WB_WDI_SP_ ┆ Population ┆ Sum        ┆ Total pop ┆ Estimates ┆ Populatio ┆ Current   ┆ Increases │
│ POP_TOTL   ┆ , total    ┆            ┆ ulation   ┆ of total  ┆ n         ┆ populatio ┆ in human  │
│            ┆            ┆            ┆ is based  ┆ populatio ┆ estimates ┆ n         ┆ populatio │
│            ┆            ┆            ┆ on t…     ┆ n …       ┆ are       ┆ estimates ┆ n,…       │
│            ┆            ┆            ┆           ┆           ┆ usual…    ┆ f…        ┆           │
│ WB_WDI_SL_ ┆ Unemployme ┆ Weighted   ┆ Unemploym ┆ The unemp ┆ The unemp ┆ While the ┆ The unemp │
│ UEM_TOTL_Z ┆ nt, total  ┆ average    ┆ ent       ┆ loyed     ┆ loyment   ┆ unemploym ┆ loyment   │
│ S          ┆ (% of      ┆            ┆ refers to ┆ comprise  ┆ rate is   ┆ ent rate  ┆ rate is a │
│            ┆ tota…      ┆            ┆ the sha…  ┆ all pe…   ┆ calcu…    ┆ ma…       ┆ use…      │
│ WB_WDI_SP_ ┆ Life       ┆ Weighted   ┆ Life expe ┆ Life expe ┆ Life expe ┆ Annual    ┆ Mortality │
│ DYN_LE00_I ┆ expectancy ┆ average    ┆ ctancy at ┆ ctancy at ┆ ctancy at ┆ data      ┆ rates for │
│ N          ┆ at birth,  ┆            ┆ birth     ┆ birth     ┆ birth is  ┆ series    ┆ different │
│            ┆ tota…      ┆            ┆ indic…    ┆ used …    ┆ de…       ┆ from      ┆ …         │
│            ┆            ┆            ┆           ┆           ┆           ┆ United…   ┆           │
│ WB_WDI_SE_ ┆ Literacy   ┆ Weighted   ┆ Adult     ┆ Literacy  ┆ The       ┆ In        ┆ Literacy  │
│ ADT_LITR_Z ┆ rate,      ┆ average    ┆ literacy  ┆ statistic ┆ indicator ┆ practice, ┆ rate is   │
│ S          ┆ adult      ┆            ┆ rate is   ┆ s for     ┆ is calcul ┆ literacy  ┆ an        │
│            ┆ total (% … ┆            ┆ the per…  ┆ most c…   ┆ ated by…  ┆ is diffi… ┆ outcome   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ in…       │
│ WB_WDI_EG_ ┆ Energy use ┆ Weighted   ┆ Energy    ┆ null      ┆ Total     ┆ The IEA   ┆ In develo │
│ USE_PCAP_K ┆ (kg of oil ┆ average    ┆ use       ┆           ┆ energy    ┆ makes     ┆ ping      │
│ G_OE       ┆ equivale…  ┆            ┆ refers to ┆           ┆ use       ┆ these     ┆ economies │
│            ┆            ┆            ┆ use of    ┆           ┆ refers to ┆ estimates ┆ growth…   │
│            ┆            ┆            ┆ pr…       ┆           ┆ the…      ┆ …         ┆           │
│ WB_WDI_NY_ ┆ GDP        ┆ Gap-filled ┆ Gross     ┆ The conce ┆ National  ┆ Gross     ┆ This      │
│ GDP_MKTP_C ┆ (current   ┆ total      ┆ domestic  ┆ ptual     ┆ accounts  ┆ domestic  ┆ indicator │
│ D          ┆ US$)       ┆            ┆ product   ┆ elements  ┆ are       ┆ product   ┆ is        │
│            ┆            ┆            ┆ is the …  ┆ of the…   ┆ compiled… ┆ (GDP), …  ┆ related   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ to t…     │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## Export data in a range of formats

### CSV

In [24]:
CSV_PATH = DATA_EXPORT_PATH / "csv"
CSV_PATH.mkdir(parents=True, exist_ok=True)

indicators.write_csv(CSV_PATH / "indicators.csv")
data.write_csv(CSV_PATH / "data.csv")
countries.write_csv(CSV_PATH / "countries.csv")

### Parquet

In [25]:
PARQUET_PATH = DATA_EXPORT_PATH / "parquet"
PARQUET_PATH.mkdir(parents=True, exist_ok=True)

# Cleat any files below the parquet path
for f in PARQUET_PATH.glob("**/*.parquet"):
    f.unlink()

# Let's pivot the data file so each indicator is a column
data_pivoted = data.pivot(
    values="value",
    index=["country_code", "year"],
    on="indicator_code"
)

# Now join with countries to get country names and regions
data_pivoted = data_pivoted.join(
    countries.select(["country_code", "country_name", "region"]),
    on="country_code",
    how="left"
)

# Write out individual parquet files, one for each year and name them accordingly
for year in range(START_YEAR, END_YEAR + 1):
    unique_file_id = uuid.uuid4().hex
    folder = PARQUET_PATH / f"year={year}"
    folder.mkdir(parents=True, exist_ok=True)
    year_data = data_pivoted.filter(pl.col("year") == year)
    year_data.write_parquet(folder / f"{unique_file_id}.parquet")

## Excel

In [26]:
# Write multiple worksheets to a single Excel file using Polars
EXCEL_PATH = DATA_EXPORT_PATH / "excel"
EXCEL_PATH.mkdir(parents=True, exist_ok=True)
with xlsxwriter.Workbook(EXCEL_PATH / "world_bank_data.xlsx") as workbook:
    data.write_excel(workbook, worksheet="Raw Data")
    countries.write_excel(workbook, worksheet="Countries")
    indicators.write_excel(workbook, worksheet="Indicators")

## JSON

In [27]:
JSON_PATH = DATA_EXPORT_PATH / "json"
JSON_PATH.mkdir(parents=True, exist_ok=True)

# Just focus on last 5 years
data_for_json = data.filter(pl.col("year") <= (END_YEAR - 5))

# Add complex column for year: value
data_for_json = data_for_json.drop_nulls("value").with_columns(pl.struct(["year", "value"]).alias("data_points"))

# Unexplode data by country, year and indicator_code
data_for_json = data_for_json.group_by(["country_code", "indicator_code"]).agg(pl.col("data_points").implode())

# Join to country
data_for_json = (
    data_for_json
    .join(
        countries.select(["country_code", "country_name", "region", "income_level", "capital_city", "latitude", "longitude"]),
        on="country_code",
        how="left"
    )
    .with_columns(pl.struct(["country_name", "region", "income_level", "capital_city", "latitude", "longitude"]).alias("country_info"))
)

# Join to indicator
data_for_json = (
    data_for_json
    .join(
        indicators.select(["indicator_code", "indicator_name", "aggregation_method"]),
        on="indicator_code",
        how="left"
    )
    .with_columns(pl.struct(["indicator_code", "indicator_name", "aggregation_method", "data_points"]).alias("indicators"))
)

data_for_json = data_for_json.group_by(["country_code", "country_info"]).agg(pl.col("indicators").implode())

list_of_countries = data_for_json["country_code"].to_list()

for country_code in list_of_countries:
    data_for_json.filter(pl.col("country_code") == country_code).write_ndjson(JSON_PATH / f"{country_code}_data.json")

## DuckDB

In [28]:
DUCKDB_PATH = DATA_EXPORT_PATH / "duckdb" / "world_bank.db"
DUCKDB_PATH.parent.mkdir(parents=True, exist_ok=True)

if DUCKDB_PATH.exists():
    # Remove the file, we want to start from scratch
    DUCKDB_PATH.unlink()

with duckdb.connect(DUCKDB_PATH) as db:

    db.sql("CREATE SCHEMA IF NOT EXISTS health_wealth_analytics")

    db.sql(
        f"""
        CREATE TABLE IF NOT EXISTS countries AS
        SELECT *
        FROM countries;
        """
    )

    db.sql(
        f"""
        CREATE TABLE IF NOT EXISTS data AS
        SELECT *
        FROM data;
        """
    )

    db.sql(
        f"""
        CREATE TABLE IF NOT EXISTS indicators AS
        SELECT *
        FROM indicators;
        """
    )

db.close()